apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiber
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: fiber/helm
    repoURL: git@github.com:r8or0pz/fiber.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 1
