name: Actions
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set Commit short SHA
      - name: Set Commit short SHA
        id: vars
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV
          echo "SHA: $SHA_SHORT"
          sed -i "s|\(tag: \).*|\1$SHA_SHORT|" "helm/values.yaml"

      # Set up Docker Buildx to build container images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log into Docker Hub (or any container registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            r8or0pz/fiber-hello:latest
            r8or0pz/fiber-hello:${{ env.SHA_SHORT }}
          push: true

      # Configure Git
      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions@ops-craft.org"

      # Version Commit and Push
      - name: Version Commit and Push
        run: |
          git add helm/values.yaml
          git commit -m "Update app version to $SHA_SHORT in values.yaml"
          git push
