name: Build and Push to ECR
on:
  push:
    branches:
      - develop

env:
  ECR_REPOSITORY: social/backend-tmp
  IMAGE_TAG: ${{ github.sha }}
  TARGET: "web"
jobs:
  build-and-push:
    name: Build and ECR Push
    runs-on: ubuntu-latest
    permissions:
      id-token: write # To enable OIDC-based authentication
      contents: read # To checkout the code
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate to AWS ECR using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/fliff-social-platform-eks-github-actions
          aws-region: ${{ vars.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: S3 ls
        run: |
          aws s3 ls