name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SHA
        run: >
          echo $GITHUB_SHA

      # Set up Docker Buildx to build container images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log into Docker Hub (or any container registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: r8or0pz/fiber-hello:${{ github.sha }}
          push: true


#      - uses: actions/checkout@v4
#      - name: Build the Docker image
#        run: >
#          VERSION=${GITHUB_SHA:0:7}
#          VALUES_FILE="helm/values.yaml"
#          IMAGE_NAME="r8or0pz/fiber-hello"
#          sed -i "s|\(tag: \).*|\1$VERSION|" $VALUES_FILE
#          docker build -t ${IMAGE_NAME}:${VERSION} .
#          docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest
#          docker push ${IMAGE_NAME}:${VERSION}
#          docker push ${IMAGE_NAME}:latest
